export default {
  Details: '/details',
  TestingComponent: '/testing-component',
  Home: '/home',
  Task: '/task',
  Projects: '/projects',
  Actions: '/actions',
  Meeting: '/meeting',
  Profile: '/profile',
  HomeStackContainer: '/home-stack-container',
  ActionsStackContainer: '/actions-stack-container',
  MeetingStackContainer: '/meeting-stack-container',
  ProfileStackContainer: '/profile-stack-container',
  BottomTabs: '/bottom-tabs',
  Login: '/login',
  SplashScreen: '/splash-screen',
};
